version: "3.9"

services:
  gui:
    build:
      context: ./GUI
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./GUI:/app
      - gui_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 200

  db:
    image: postgres:16
    container_name: pg_pizza
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pizza-manufacture
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: api_pizza
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5003
      ConnectionStrings__Default: "Host=db;Port=5432;Database=pizza-manufacture;Username=postgres;Password=root"
    ports:
      - "5003:5003"
    restart: unless-stopped

volumes:
  gui_node_modules:
  pgdata:
